# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/2.8.5/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/2.8.5/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/Cellar/cmake/2.8.5/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alexei/src/luma/HTTP-Live-Video-Stream-Segmenter-and-Distributor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alexei/src/luma/HTTP-Live-Video-Stream-Segmenter-and-Distributor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/2.8.5/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/2.8.5/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alexei/src/luma/HTTP-Live-Video-Stream-Segmenter-and-Distributor/CMakeFiles /Users/alexei/src/luma/HTTP-Live-Video-Stream-Segmenter-and-Distributor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alexei/src/luma/HTTP-Live-Video-Stream-Segmenter-and-Distributor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named segmenter

# Build rule for target.
segmenter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 segmenter
.PHONY : segmenter

# fast build rule for target.
segmenter/fast:
	$(MAKE) -f CMakeFiles/segmenter.dir/build.make CMakeFiles/segmenter.dir/build
.PHONY : segmenter/fast

options_parsing.o: options_parsing.c.o
.PHONY : options_parsing.o

# target to build an object file
options_parsing.c.o:
	$(MAKE) -f CMakeFiles/segmenter.dir/build.make CMakeFiles/segmenter.dir/options_parsing.c.o
.PHONY : options_parsing.c.o

options_parsing.i: options_parsing.c.i
.PHONY : options_parsing.i

# target to preprocess a source file
options_parsing.c.i:
	$(MAKE) -f CMakeFiles/segmenter.dir/build.make CMakeFiles/segmenter.dir/options_parsing.c.i
.PHONY : options_parsing.c.i

options_parsing.s: options_parsing.c.s
.PHONY : options_parsing.s

# target to generate assembly for a file
options_parsing.c.s:
	$(MAKE) -f CMakeFiles/segmenter.dir/build.make CMakeFiles/segmenter.dir/options_parsing.c.s
.PHONY : options_parsing.c.s

segmenter.o: segmenter.c.o
.PHONY : segmenter.o

# target to build an object file
segmenter.c.o:
	$(MAKE) -f CMakeFiles/segmenter.dir/build.make CMakeFiles/segmenter.dir/segmenter.c.o
.PHONY : segmenter.c.o

segmenter.i: segmenter.c.i
.PHONY : segmenter.i

# target to preprocess a source file
segmenter.c.i:
	$(MAKE) -f CMakeFiles/segmenter.dir/build.make CMakeFiles/segmenter.dir/segmenter.c.i
.PHONY : segmenter.c.i

segmenter.s: segmenter.c.s
.PHONY : segmenter.s

# target to generate assembly for a file
segmenter.c.s:
	$(MAKE) -f CMakeFiles/segmenter.dir/build.make CMakeFiles/segmenter.dir/segmenter.c.s
.PHONY : segmenter.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... segmenter"
	@echo "... options_parsing.o"
	@echo "... options_parsing.i"
	@echo "... options_parsing.s"
	@echo "... segmenter.o"
	@echo "... segmenter.i"
	@echo "... segmenter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

